# Generated by Django 6.1 on 2026-09-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soosapp', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_writer', models.CharField(max_length=14)),
                ('b_email', models.EmailField(max_length=50)),
                ('b_subject', models.CharField(max_length=50)),
                ('b_date', models.DateTimeField()),
                ('b_contents', models.CharField(max_length=50)),
                ('b_file', models.FileField(max_length=255, upload_to='uploads/%Y/%m/%d/')),
                ('b_orgfile', models.CharField(max_length=255)),
                ('b_filesize', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(max_length=255, upload_to='uploads/%Y/%m/%d/')),
                ('orgfile', models.CharField(max_length=255)),
                ('filesize', models.IntegerField(default=0)),
                ('rdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
