# Generated by Django 6.1 on 2026-09-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotapp', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(db_column='ORDER_ID', primary_key=True, serialize=False)),
                ('order_type', models.IntegerField(choices=[(1, '입고'), (2, '출고')], db_column='TYPE')),
                ('req_time', models.DateTimeField(db_column='REQ_TIME')),
                ('end_time', models.DateTimeField(blank=True, db_column='END_TIME', null=True)),
                ('due_time', models.DateTimeField(db_column='DUE_TIME')),
                ('priority', models.IntegerField(choices=[(1, '일반'), (2, '긴급')], db_column='PRIORITY', default=1)),
                ('status', models.IntegerField(choices=[(0, '대기'), (1, '진행'), (2, '완료'), (3, '취소'), (4, '지연')], db_column='STATUS', default=0)),
            ],
            options={
                'db_table': 'ORDER_TABLE',
            },
        ),
    ]
