# Generated by Django 6.1 on 2026-09-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robotapp', '0003_order'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='robotapp_order',
        ),
    ]
