# Generated by Django 6.1 on 2026-09-04 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotapp', '0004_alter_order_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(db_column='LOCATION_ID', primary_key=True, serialize=False)),
                ('location_code', models.IntegerField(db_column='LOCATION_CODE')),
                ('x_coord', models.FloatField(db_column='X_COORD')),
                ('y_coord', models.FloatField(db_column='Y_COORD')),
                ('z_coord', models.FloatField(db_column='Z_COORD')),
                ('state', models.IntegerField(db_column='STATE')),
                ('max_storage', models.FloatField(db_column='MAX_STORAGE')),
                ('cur_storage', models.FloatField(db_column='CUR_STORAGE')),
            ],
            options={
                'db_table': 'robotapp_location',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.AutoField(db_column='ZONE_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=50)),
                ('state', models.IntegerField(db_column='STATE')),
                ('org_x', models.FloatField(db_column='ORG_X')),
                ('org_y', models.FloatField(db_column='ORG_Y')),
                ('org_z', models.FloatField(db_column='ORG_Z')),
                ('width', models.FloatField(db_column='WIDTH')),
                ('length', models.FloatField(db_column='LENGTH')),
                ('height', models.FloatField(db_column='HEIGHT')),
            ],
            options={
                'db_table': 'robotapp_zone',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(db_column='ITEM_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=50)),
                ('width', models.FloatField(db_column='WIDTH')),
                ('length', models.FloatField(db_column='LENGTH')),
                ('height', models.FloatField(db_column='HEIGHT')),
                ('item_class', models.IntegerField(db_column='CLASS')),
                ('incoming_date', models.DateTimeField(db_column='INCOMING_DATE')),
                ('location', models.ForeignKey(blank=True, db_column='LOCATION_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='robotapp.location')),
            ],
            options={
                'db_table': 'robotapp_item',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(db_column='INVENTORY_ID', primary_key=True, serialize=False)),
                ('cur_item_num', models.IntegerField(db_column='CUR_ITEM_NUM')),
                ('min_item_num', models.IntegerField(db_column='MIN_ITEM_NUM')),
                ('item', models.ForeignKey(db_column='ITEM_ID', on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='robotapp.item')),
                ('location', models.ForeignKey(db_column='LOCATION_ID', on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='robotapp.location')),
            ],
            options={
                'db_table': 'robotapp_inventory',
            },
        ),
        migrations.CreateModel(
            name='AMR',
            fields=[
                ('amr_id', models.AutoField(db_column='AMR_ID', primary_key=True, serialize=False)),
                ('robot_state', models.IntegerField(db_column='ROBOT_STATE')),
                ('operation_state', models.IntegerField(db_column='OPERATION_STATE')),
                ('battery', models.FloatField(db_column='BATTERY')),
                ('location', models.ForeignKey(blank=True, db_column='LOCATION_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amrs', to='robotapp.location')),
            ],
            options={
                'db_table': 'robotapp_amr',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('order_detail_id', models.AutoField(db_column='ORDER_DETAIL_ID', primary_key=True, serialize=False)),
                ('item_num', models.IntegerField(db_column='ITEM_NUM')),
                ('item', models.ForeignKey(db_column='ITEM_ID', on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='robotapp.item')),
                ('order', models.ForeignKey(db_column='ORDER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='robotapp.order')),
            ],
            options={
                'db_table': 'robotapp_order_detail',
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('order_history_id', models.AutoField(db_column='ORDER_HISTORY_ID', primary_key=True, serialize=False)),
                ('pre_state', models.IntegerField(db_column='PRE_STATE')),
                ('change_state', models.IntegerField(db_column='CHANGE_STATE')),
                ('status', models.IntegerField(db_column='STATUS')),
                ('order_date', models.DateTimeField(db_column='ORDER_DATE')),
                ('order', models.ForeignKey(db_column='ORDER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='robotapp.order')),
            ],
            options={
                'db_table': 'robotapp_order_history',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(db_column='TASK_ID', primary_key=True, serialize=False)),
                ('task_time', models.DateTimeField(db_column='TASK_TIME')),
                ('priority', models.IntegerField(db_column='PRIORITY', default=1)),
                ('status', models.IntegerField(choices=[(0, '대기'), (1, '진행'), (2, '완료'), (3, '취소')], db_column='STATUS', default=0)),
                ('start_time', models.DateTimeField(blank=True, db_column='START_TIME', null=True)),
                ('end_time', models.DateTimeField(blank=True, db_column='END_TIME', null=True)),
                ('amr', models.ForeignKey(blank=True, db_column='AMR_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='robotapp.amr')),
                ('end_location', models.ForeignKey(blank=True, db_column='END_LOCATION_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_tasks', to='robotapp.location')),
                ('item', models.ForeignKey(blank=True, db_column='ITEM_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='robotapp.item')),
                ('order', models.ForeignKey(blank=True, db_column='ORDER_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='robotapp.order')),
                ('start_location', models.ForeignKey(blank=True, db_column='START_LOCATION_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_tasks', to='robotapp.location')),
            ],
            options={
                'db_table': 'robotapp_task',
            },
        ),
        migrations.CreateModel(
            name='TaskRecord',
            fields=[
                ('task_record_id', models.AutoField(db_column='TASK_RECORD_ID', primary_key=True, serialize=False)),
                ('x_coord', models.FloatField(db_column='X_COORD')),
                ('y_coord', models.FloatField(db_column='Y_COORD')),
                ('z_coord', models.FloatField(db_column='Z_COORD')),
                ('record_time', models.DateTimeField(db_column='RECORD_TIME')),
                ('task_status', models.IntegerField(db_column='TASK_STATUS')),
                ('task', models.ForeignKey(db_column='TASK_ID', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='robotapp.task')),
            ],
            options={
                'db_table': 'robotapp_task_record',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='zone',
            field=models.ForeignKey(db_column='ZONE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='robotapp.zone'),
        ),
    ]
