# Generated by Django 6.1 on 2026-09-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotapp', '0005_location_zone_item_inventory_amr_orderdetail_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='amr',
            constraint=models.UniqueConstraint(condition=models.Q(('location__isnull', False)), fields=('location',), name='unique_amr_location'),
        ),
    ]
