# Generated by Django 5.2.6 on 2026-09-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotapp', '0006_amr_unique_amr_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, '일반'), (2, '긴급')], db_column='PRIORITY', default=1),
        ),
    ]
