"""
Django settings for pj_django project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#<1> BASE_DIR 하위에 추가
BASE_DIR = Path(__file__).resolve().parent.parent
DEPLOY = False #Default 개발시
#DEPLOY = True #PythonAnywhere에 올릴 때만 True로 설정


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6))ojkra0tv%&e217n7)a!2n1)3dv6h_uy266*aj-hbg8s@tmw'

# SECURITY WARNING: don't run with debug turned on in production!
#<2> ALLOWED_HOSTS 변경
#DEBUG = True
DEBUG = not DEPLOY
if DEPLOY:
    ALLOWED_HOSTS = ['lyi.pythonanywhere.com']
    CSRF_TRUSTED_ORIGINS = ['https://lyi.pythonanywhere.com']
else:
    #ALLOWED_HOSTS = []
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '192.168.1.35']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'soosapp.apps.SoosappConfig',
    'robotapp.apps.RobotappConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pj_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pj_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

#<3> DATABASES 변경
#if DEPLOY:
if True:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'django_schema',
            'USER': 'django',
            'PASSWORD': '1234',
            'HOST': '127.0.0.1',
            'PORT': '3306',
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

#USE_TZ = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

#<4> 추가/확인
STATIC_URL = '/static/' #변경: /추가
STATIC_ROOT = BASE_DIR / 'staticfiles' #추가

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

#추가
if DEPLOY: 
    MAX_UPLOAD_MB = 2  # 2MB
else:
    MAX_UPLOAD_MB = 5  # 5MB


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

SESSION_COOKIE_AGE = 1800 # 30분 (초 단위)
SESSION_SAVE_EVERY_REQUEST = True